# Generated by Django 2.0.5 on 2018-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_auto_20180722_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='category',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='ptype',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weakness',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
