# Generated by Django 2.0.5 on 2018-07-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0004_auto_20180722_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
    ]
