# Generated by Django 2.0.5 on 2018-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0005_remove_pokemon_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
